### ISSUE TITLE
キービジュアル実装前の仕様作成・言語化

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#1]
@TomoyukiHata さんにTHREEJSの実装可否判断を任せる
3/1 am で判断する

その前に実装したいキーヴィジュアルの仕様を言語化する（外に簡単になげれるように）

@nishidai-andaze がレビューしてみる（その仕様書が理解できるか・想像できるか・外に出した人へのシミュレーションも兼ねる）

**Comment by TomoyukiHata** [comment]
2/25時点進捗です。

パーティクルアニメーション

	-Three.js使用

		-パーティクルが集合してロゴを形成
			ロゴ画像の読み込み、WebGL用にデータ変換
			メッシュ　→　パーティクルに変換

		-色が異なる複数のパーティクル

		-ドラッグするとカメラがゆっくり移動（ディレイあり）
			OrbitControlで制御

		-ドラッグ時にロゴにカーソルが触れている場合は、パーティクルが拡散する
			Raycasterでロゴを検出
			光線にあたった物体を取得した場合のみイベントを設定
			
		-拡散したパーティクルは自動的にもとの位置に集合する

**Comment by TomoyukiHata** [comment]
処理の流れを意識して更新します。

-初期挙動

	-画面ロード
		-カメラのセット
			-位置

		-シーンのセット
			-画面幅、高さ、背景色

		-レンダリング

	-ロゴ画像読み込み（カラー画像）

	-WebGL用にデータ変換

	-メッシュ形状からパーティクルに変換

	-ロゴマーク + 文字（a, n, d, a, z, e）　に分割してマテリアル化



-インタラクション

	-画面をドラッグ
		-ドラッグされた方向にカメラが移動（OrbitControl）

			-カメラの移動範囲はロゴが正面から見える角度に制限
			 （ロゴ後方には回り込めない）

				-初期位置に移動

		-カメラが画面に近づく

			-拡大によりロゴが画面外に見切れることはない

				-初期位置に移動

		-Raycaster起動

			-マテリアルが検出された場合

				-パーティクルが拡散

					-初期位置に移動

			-マテリアルが検出されない場合

				-イベントなし

	-画面をクリック

		-イベントなし

	-画面をスクロール

		-イベントなし
