### ISSUE TITLE
Create Shortcode for call partial in markdown 

### ISSUE THREAD

**Issue by ameio-developer** [andaze/WebCorporate#132]
- [ ] Create shortcode for call partial file in shortcode

**Comment by nishidai-andaze** [comment]
The following code could be used to get the section information in themes\andaze\layouts\shortcodes\servicelist.html.
This means that single pages, for example, do not need to specify the section as a parameter.

Also, if you want to pass section information from the home page or directly from a template, you should continue to utilize scratch.


```
<div class="bg-black flex text-white">

    <div>
        {{ with .Page }}
            {{ .Section }}
        {{ end }}
    </div>

    {{ .Scratch.Set "section" "services" }}
        {{ partial "atom-irnews-heading.html" . }}
    {{.Scratch.Delete "section" }}
    
</div>
```

If the same component is to be used from both templates or shortcodes, use the elseif syntax with or without scratch information, and the last else without scratch information.
It would be better to do so.
