### ISSUE TITLE
キービジュアルの色変更

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#165]
dip と丸かぶりはよくない
カラージェネレーターとかつかってよしなにやって色を選んで設定してほしい

**Comment by TomoyukiHata** [comment]
色変更前
![before](https://user-images.githubusercontent.com/100174879/168687505-c02f6465-2c72-4157-bb5a-94d12d109629.png)

**Comment by TomoyukiHata** [comment]
色変更後
![after](https://user-images.githubusercontent.com/100174879/168687984-52290e1c-5777-404f-9e3a-6e72eb5ec39c.png)
