### ISSUE TITLE
Change to function call type execution method

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#246]
# Purpose

- Introduced swup, but no animation is fired on the second and subsequent accesses to the top page because the load event is not triggered (well, it's SPA-like, so that's not surprising).

# Strategy
- We would like to change to a method that hooks into swup events, referring to https://swup.js.org/getting-started/reloading-javascript.
- Instead of hooking the main function that handles the top page animation directly to the DOM event (load), I want to call a specific main function after the load event.

@TomoyukiHata

**Comment by nishidai-andaze** [comment]
@TomoyukiHata This issue, I'll change it here to get it done quickly. It will probably only take a few lines.

**Comment by nishidai-andaze** [comment]
Switch to the js module, but keep it to a rearrangement once, including the skill level.

**Comment by nishidai-andaze** [comment]
#103 issue of swup was able to be introduced in its entirety.

And then we can kill this main issue.

**Comment by nishidai-andaze** [comment]
Hmmm, this is an endless separation of codes.
Lack of scope, modules, functional programming. That's the negative side of vanilla JS.

**Comment by TomoyukiHata** [comment]
I couldn’t understand why, but when I remove "transition property" from div-tag for loading,
white-out with page-transition never never happened.
![スクリーンショット 2022-05-30 135847](https://user-images.githubusercontent.com/100174879/170920012-20a94bce-2db1-4894-bc7e-ef88c682a5ca.png)

**Comment by TomoyukiHata** [comment]
key-visual animation never work after second visit.

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
I made loading icon shown when we visit top-page.
I`ve finished working on this issue related to key-visual.
