### ISSUE TITLE
https://www.figma.com/file/uDqozBvQAiFg1PqQ9vjwnb/andaze?node-id=21%3A219

### ISSUE THREAD

**Issue by tomoran** [andaze/WebCorporate#26]
https://www.figma.com/file/uDqozBvQAiFg1PqQ9vjwnb/andaze?node-id=21%3A219

**Comment by nishidai-andaze** [comment]
該当コンテンツ=IR NEWS が無いため実装を保留する

**Comment by nishidai-andaze** [comment]
ブランチが古いためイシューもろとも再作成とする（重複作業） close #26
