### ISSUE TITLE
マークダウンコンテンツの過不足の解消

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#262]
- [x] サンプルコンテンツの削除
- [x] 原稿と比較して大まかにあっているか（原稿にサイトコンテンツを合わせる）
- [x] 既存サイト(andaze.com) のコンテンツが入っているのは問題ないとする。

**Comment by TomoyukiHata** [comment]
texts of service section is OK

**Comment by TomoyukiHata** [comment]
texts of top mesagen is OK

**Comment by TomoyukiHata** [comment]
texts of top corporate slogan is OK

**Comment by TomoyukiHata** [comment]
checked about-page

**Comment by TomoyukiHata** [comment]
contents of solution-page is different from manuscript.

**Comment by TomoyukiHata** [comment]
checked case-study-page

**Comment by TomoyukiHata** [comment]
update design of texts of all pages

**Comment by TomoyukiHata** [comment]
update design of top-page

**Comment by TomoyukiHata** [comment]
update design of reason-page
