### ISSUE TITLE
Image Ratio Adjustment

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#287]
Don't distort ratios with object-fit covers

**Comment by nishidai-andaze** [comment]
![image](https://user-images.githubusercontent.com/99951437/172405290-24ff09af-0260-45ff-8ade-9c1a5fdb67f3.png)

**Comment by TomoyukiHata** [comment]
change picture in the director
![スクリーンショット 2022-06-10 140719](https://user-images.githubusercontent.com/100174879/172994364-bc3735d6-a6c0-44c8-973e-45a74e38cc43.png)
y
