### ISSUE TITLE
button enable/disable functionality stoped

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#293]
https://dev.andaze.com/ja/contact

**Comment by ameio** [comment]
@nishidai-andaze 
Yes this is stoped after add new packaged of node 
let us check how we can enable

**Comment by nishidai-andaze** [comment]
Situation.

* Contact page does not fire when navigating from other pages (script is not recognized).
* Fires when reloading the contact page directly

Prediction
* Page transitions by swup do not fire load, domcontentload events, etc.
* Also, if the script is in a solid state, it will not be re-executed (only replaced).

Countermeasures
* Switch to event-driven method.
* Re-execute all scripts (but this is heavy)
