### ISSUE TITLE
ボックスのデザインがディップのマルパクリになっている

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#403]
- ボックス中にある線がDIPと同一
- コードからまるパクリになっているとまずい

![image](https://user-images.githubusercontent.com/60770505/176823932-fafe4ea5-2455-41bf-9f58-e4abc3b89bdc.png)

**Comment by TomoyukiHata** [comment]
コードを丸パクリではないですが、ラインは削除します
