### ISSUE TITLE
日本語の原稿を変更したい場合の手順が知りたい

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#411]
- 事務員でも変更できるような手順はありますか？

**Comment by nishidai-andaze** [comment]
[fores](https://app.forestry.io/sites/ly8ghrslvcgofg/#/settings) および [Admin](https://andaze.com/admin/#/login) の設置を持って完了

https://watch.screencastify.com/v/vr8dE8St69T9OSm1J1mf
