### ISSUE TITLE
原稿の不足箇所

### ISSUE THREAD

**Issue by TomoyukiHata** [andaze/WebCorporate#443]
以下、現時点（2022/7/8）での不足箇所

**サービス**
【シェアードチーム】

- アンダーズが選ばれる理由
- プロジェクト成功を支える“シェアード・チーム”
-----------------------------------------
![スクリーンショット 2022-07-07 205249](https://user-images.githubusercontent.com/100174879/177890161-6ba05ce1-2df9-4295-999a-d5a85da6bc68.png)
-----------------------------------------

【クラウド、コンサルティング、UI/UXデザイン、新規事業サービス開発】

- 事例紹介
-----------------------------------------
![スクリーンショット 2022-07-07 205626](https://user-images.githubusercontent.com/100174879/177890175-df048237-35d7-4af4-9d3a-9506b781d2a1.png)
-----------------------------------------

------

**ソリューション**
【B2C】

- 事例紹介
-----------------------------------------
![スクリーンショット 2022-07-08 083631](https://user-images.githubusercontent.com/100174879/177888654-d07f797e-f1dd-4c8f-8f58-727c7bc37a85.png)
-----------------------------------------

------

**サステナビリティ**
【情報セキュリティマネジメント】

- 適用範囲
- 認証規格
- 認証対象サービス
-----------------------------------------
![スクリーンショット 2022-07-08 084313](https://user-images.githubusercontent.com/100174879/177889592-94bab838-1550-499f-83da-128b8452f689.png)
-----------------------------------------

【資源の有効活用】

- 3R（リデュース、リユース、リサイクル）の推進
- OA機器の節電対策
-----------------------------------------
![スクリーンショット 2022-07-08 084733](https://user-images.githubusercontent.com/100174879/177889594-afd2972b-c95c-40ea-bf10-8561ce8ef25c.png)
-----------------------------------------

**Comment by TomoyukiHata** [comment]
@yofujimaki  cc @nishidai-andaze 
上記通り、原稿に不足箇所があります。

不足箇所を非表示にするか、新たにテキストを追加するか
いかがいたしましょうか？


サービスページとソリューションページの不足箇所については
非表示対応でも成立すると思われますが、

サステナビリティページの不足箇所については
非表示するとかなり寂しい印象になりそうです。

**Comment by yofujimaki** [comment]
@TomoyukiHata  タイトルのみ存在している（テキストなし）ものについては、削除でお願いします。
