### ISSUE TITLE
Bug And Suggestion In EN

### ISSUE THREAD

**Issue by ameio-developer** [andaze/WebCorporate#462]
@nishidai-andaze 

As per our checking we have following point but we are not sure all are needed for release 1 
So please create issue from following point which you think needed for release 1

Bug
====================================

1) In Contact Page all field look like required but Validation not working. please put Validation

![image](https://user-images.githubusercontent.com/79352313/178207625-9449d4e7-ee04-430c-b268-dcf1cb8678d2.png)

Suggestion
===================================

1) https://dev.andaze.com/en/company/about/
![image](https://user-images.githubusercontent.com/79352313/178207813-fc28009c-2e90-4f11-b6aa-9d4e2ca275fa.png)

2) https://dev.andaze.com/en/reason
![image](https://user-images.githubusercontent.com/79352313/178208473-841f65e0-cb5e-4dd1-bc7a-d3f1bfb5e51f.png)

3) Please change header image icon is not look good in services detail pages 
![image](https://user-images.githubusercontent.com/79352313/178208565-eb99dd9d-2b7f-47b2-abe0-d0d10da4c52a.png)

4) Please change all slider image for improve design look in solution detail pages
![image](https://user-images.githubusercontent.com/79352313/178208756-65a5ff74-2062-4de8-9f74-c1f9ac373389.png)

5) [professional-image](https://dev.andaze.com/en/professional-images/) I think it should not to show as a list page or detail page 
![image](https://user-images.githubusercontent.com/79352313/178209375-1b8131a4-1494-46a9-83d6-2efbe7b462d1.png)

6) After redirect from other page to home page designing issue
![image](https://user-images.githubusercontent.com/79352313/178209694-7bba3988-f788-49b7-86a7-5a4c4405a559.png)

7) Please crop image
![image](https://user-images.githubusercontent.com/79352313/178209795-32aa094a-1d0c-4c39-8d77-1fe30482eca8.png)

8) Please change title
![image](https://user-images.githubusercontent.com/79352313/178210049-7ba10e67-c746-4b91-89ff-656e2bf95372.png)

9) Hide slider button
![image](https://user-images.githubusercontent.com/79352313/178210094-4b48f6a9-069f-4e0b-9428-b957f56058f3.png)

10) Change title 
![image](https://user-images.githubusercontent.com/79352313/178210173-74c13dcb-dc33-4102-a380-904a9be68e7c.png)

**Comment by TomoyukiHata** [comment]
@ameio-developer @nishidai-andaze 
Suggestion 6, 7, 8 are in the process of being fixed.
These will be improved after next PR merging.

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
when it comes to Japanese end, 
I think there is no critical issue except for below

https://github.com/andaze/WebCorporate/issues/454
(fixing is on progress)

of course I don't think design is perfect

**Comment by TomoyukiHata** [comment]
Suggestion 10 fixed
pushed to main branch
