### ISSUE TITLE
全体的に画像のロードが遅い

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#481]
- サイズとJPEGクオリティーがWEB用に最適化されてない

以下は前バージョンの画像最適化のやり方（参考まで）

主に使っていたのは以下
https://github.com/andaze/hugo-amp-corporate/blob/master/themes/andaze/layouts/shortcodes/img.html
https://github.com/andaze/hugo-amp-corporate/blob/master/themes/andaze/layouts/shortcodes/responsive-img.html
https://github.com/andaze/hugo-amp-corporate/blob/master/themes/andaze/layouts/shortcodes/fixed-img.html

**Comment by nishidai-andaze** [comment]
- [ ] 最適化の指針を決める（最多でいくつのデバイス・解像度の画像を用意するのか）
- [ ] 既存コードを解読する

**Comment by nishidai-andaze** [comment]
なぜ、サンプルコードは表示サイズごとにショートコードが違うのか。

**Comment by nishidai-andaze** [comment]
https://tailwindcss.com/docs/responsive-design#customizing-breakpoints

この基準をバリエーションを作る基準とする

small: < 640px 
middle: < 1024px
large: < 1280px
extra large: < 1600px
most large: < 1920px

**Comment by nishidai-andaze** [comment]
![image](https://user-images.githubusercontent.com/99951437/180422191-94e8fc87-36bf-4892-aee9-1c70d93dbc8b.png)

大体ざっくりサイズの概要図・表。同じ色は同じサイズ

**Comment by nishidai-andaze** [comment]
具体的に一時実装としては添付画像サムネイルを適切に生成するようにする。

![image](https://user-images.githubusercontent.com/99951437/180424190-119497e8-3a84-4626-841a-aef96626b6ae.png)

**Comment by nishidai-andaze** [comment]
name : picture.html

**Comment by nishidai-andaze** [comment]
画像最適化ショートコードないしテンプレートの作成完了

**Comment by nishidai-andaze** [comment]
`Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
The content server has rejected the request with: BadRequest
Reason: The size of the app content was too large. The limit for this Static Web App is 524288000 bytes.`


ということで、azure の制限にひっかかった。
画像の最適化配信のために多数の解像度の画像を生成し、それをデプロイコンテンツとして含めると余裕で 500mb を超える。
これは現実的に使い物にならない可能性あり。

**Comment by nishidai-andaze** [comment]
https://docs.microsoft.com/en-us/azure/static-web-apps/plans

**Comment by nishidai-andaze** [comment]
画像の最適化は完了
