### ISSUE TITLE
Key visuals behave incorrectly when accessed for the first time.

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#482]
- [ ] シークレットウィンドウを開く
- [ ] andaze.com をブラウザで開く。ロード完了後に一瞬パーティクル集約後のロゴ？が見える。その後離散から集約するアニメーションへ遷移する

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
低確率ですが発生しますね。確認します。

**Comment by TomoyukiHata** [comment]
オブジェクト読み込み　→　アニメーション準備完了　→　ローディング画面外す
順番に処理を組んでいく必要あり
