### ISSUE TITLE
iphone 13のEdgeでトップ画面がリロードを繰り返す

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#484]
- 資料はiphoneのbraveブラウザでのキャプチャ
- iPhone Edgeで再現

https://user-images.githubusercontent.com/60770505/179448762-3e6e6d57-ff90-427b-8be0-e51bd9448556.mp4

**Comment by nishidai-andaze** [comment]
@TomoyukiHata bug 系優先度高く対応してください

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
実機でのデバッグが必須です。

自分のiphone8でも事象再現できたので実機については問題ないです。
デバッグ環境についてが問題かと。

例えば、Three.jsの記述を全部コメントアウトして事象が直るか確認したい場合、
修正・デプロイして確認することはできますか？

今のandaze.comがすでに一般公開されているなら、この方法はできないと思うので念のため確認です。

**Comment by nishidai-andaze** [comment]
@TomoyukiHata なるほど、了解。
実機デバッグはいずれかの段階で必要になるとは思っていたのでまぁ想定内です。

ステージング環境としては以下のいずれかを利用します。

-  dev.andaze.com 
-  [azure static web app の純正機能](https://docs.microsoft.com/en-us/azure/static-web-apps/overview) 

また実機デバッグの方法としては以下が考えられ、いずれかで実施できるように環境整備のリクエストをシステム部または @yofujimaki san に相談します。

1. https://www.browserstack.com/
2. XCode / iOS simulator の利用（手持ちmacbook環境・非アクティブトラック環境）
3. [Remoted iOS Simulator for Windows - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/)

蛇足で、VMのOSでmacOS選べないのか？（制作過程でもキーコード的に効率的）情シスに質問しておきます。
他デバッグ方法について良い方法があればお知らせください。

**Comment by nishidai-andaze** [comment]
@TomoyukiHata ちとデバッグ環境について勘違いな回答をしたが、アクティブトラックで追跡できることを前提として、browserstack に順次切り替えをお願いします。 （準備でき次第 fujimaki san より通知あり）

**Comment by nishidai-andaze** [comment]
@TomoyukiHata https://accounts.browserstack.com/jointeam/1fd6f502a54c4605a832d446136a0302 から参加して利用を開始してください。ライセンスが１つしかないので同時利用してそうなときはチャットで声掛けをお願いします。

@ameio Please ask for the Indian team when you use them.

**Comment by ameio** [comment]
@nishidai-andaze 
mostly we try to use when your office time off
before we take control we will inform in group 

Thank you for your invitation
