### ISSUE TITLE
トップのアニメーションが見えなくなったときは動作を停止する

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#513]
- CPU消費を抑えるため
- DIPのように（ビデオ添付）
- 優先度は低

https://user-images.githubusercontent.com/60770505/180731051-070ae1bf-a251-4cba-a1f9-4d3c5a285f86.MP4

**Comment by nishidai-andaze** [comment]
@TomoyukiHata こちら終わっていますか？

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
今、andaze.comで動作確認し、完了です。

以下の場合でアニメーション停止
- タブが非アクティブの場合
- トップページ以外にいる場合
- トップページをスクロールしてロゴが見えなくなった場合
