### ISSUE TITLE
ページが応答しないエラーあり

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#590]
- とある従業員のマシンでちょくちょく発生するとのことで報告あり
- 再現できなくても、コードベースで見直し、予防的対応を求む

![image](https://user-images.githubusercontent.com/60770505/194184223-857767be-79ce-47d8-b1ef-75d3bb07c572.png)

**Comment by TomoyukiHata** [comment]
JSエラーが大量発生して処理が重くなったことが原因か
以下で対処したのでclose
https://github.com/andaze/WebCorporate/pull/565
