### ISSUE TITLE
代表取締役の写真が風景になっている

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#600]
①表題の通り
②藤巻さんのタイトルを「シニアコンサルタント」に変更
![image](https://user-images.githubusercontent.com/60770505/195478894-a8048407-0614-40ff-be46-bc9bef4ce3d6.png)

**Comment by TomoyukiHata** [comment]
JSのエラーが原因？
![スクリーンショット 2022-10-31 143646](https://user-images.githubusercontent.com/100174879/198938929-78531865-a468-49de-a797-57637a32dcbd.png)

**Comment by TomoyukiHata** [comment]
JSのエラーが原因？
このページでキャッシュクリアしてエラーを消しても、画像に変化なし
![スクリーンショット 2022-10-31 143646](https://user-images.githubusercontent.com/100174879/198939353-86546197-42ce-4acd-9e24-c666746bdcd5.png)

**Comment by TomoyukiHata** [comment]
エラーがないのに画像がおかしい（デフォルト表示）
不定期に発生する。画像が読み込まれていない？
![スクリーンショット 2022-11-02 092213](https://user-images.githubusercontent.com/100174879/199366249-f0d39730-3c24-4ad2-93c6-e5acd6d8b61d.png)

**Comment by TomoyukiHata** [comment]
コードから考えると、srcに画像パスがセットされていないからデフォルト画像が表示される
何らかの原因で以下のif文の中に入る場合と入らない場合がある様

そもそもif文をなくせば解決するように見える

```
{{ if .Page.Params.image }}
　 {{ .Scratch.Set "src" .Page.Params.image }}
{{ end }}
```

**Comment by nishidai-andaze** [comment]
まぁ普通に考えてほかが正常挙動だし指定の仕方に難ありなんでしょう。
もしくはアセット配置位置が間違ってるとか

見てみよう

**Comment by nishidai-andaze** [comment]
それにしても面白いなこれは

**Comment by nishidai-andaze** [comment]
なるほど。

- ローカルだと再現しない
- https://andaze.com/ja/services/consulting/ だと症状あり
- https://andaze.com/ja/services/cloud/ だと症状なし

**Comment by nishidai-andaze** [comment]
ローカルだとなんどやっても発生しない
臭うところは scratch src が広範囲でグローバルで使われているところ
並列処理をしているHUGOの仕様、排他制御のバグが臭う

**Comment by nishidai-andaze** [comment]
無駄な処理もついでに見直そす

**Comment by nishidai-andaze** [comment]
条件文を精査して無駄を取り除いたらまぁいけるか
