### ISSUE TITLE
YouTubeのコンテンツをトップページに表示

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#604]
- 会社概要だけでなく、チャンネル内のサムネールを複数取得して、サイト上に表示
- 技術的に、制限があればそれに従う

![image](https://user-images.githubusercontent.com/60770505/195509097-70953756-65bb-4127-8d78-ee7c9543d089.png)

**Comment by nishidai-andaze** [comment]
https://gohugo.io/templates/data-templates/#get-remote-data

**Comment by TomoyukiHata** [comment]
https://github.com/andaze/WebCorporate/pull/647#issuecomment-1309640861
