### ISSUE TITLE
モバイルでトップ画面をリサイズすると、スクロールしなくなる

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#611]
- アニメーションを動かすために、スワイプ動作を含むため、このようなことが起こりえる

https://user-images.githubusercontent.com/60770505/196836981-62be915c-034f-4280-bac7-a54953670477.MOV

**Comment by TomoyukiHata** [comment]
@yofujimaki 
私のモバイルでは再現しませんでした。
コードベースでエラーを修正したので、現象が再現するか
ご確認よろしくお願いいたします。

**Comment by yofujimaki** [comment]
@TomoyukiHata  治っていると思います。
