### ISSUE TITLE
LPにはGoogleアナリティクスを連携させ、流入経路をわかるようにする

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#625]

**Comment by nishidai-andaze** [comment]
@andashish Please grant Google Analaytics permissions to nishidai@andaze.com to accomplish this task.

**Comment by andashish** [comment]
@nishidai-andaze Currently I don't have enough privilege to grant you permission. I will grant it after I receive priviledge from Fujimaki-san.

@yofujimaki I have requested access for this, could you approve it?

**Comment by nishidai-andaze** [comment]
@andashish Thank you for your reply. I will bill Mr. Fujimaki.
Apart from this, please also invite me to Google AdWords if possible. (Is Mr. Fujimaki authorized to do this as well?)

**Comment by nishidai-andaze** [comment]
This one is self-resolved.
