### ISSUE TITLE
Googleに「salesforce」のアドセンス設定

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#626]
タイトル：
20人以上なら永年使える買い切りのCRM
リード：
業種を問わず利用できるPaaS型のCRMツールで、カスタマイズを自社資産に蓄積
飛び先：
https://andaze.com/lp/paas-no-susume/
金額：
1日500円上限、クリック当たり最低額

**Comment by nishidai-andaze** [comment]
@yofujimaki 

yofujimaki@andaze.com 宛にAdWords の招待を送りましたので承認をお願いします。


なお、以下理由により**一時的にこちらの社用クレジット情報を入力していますので変更をお願いします。**
(500円/日の予算なので数カ月はゆうに持つかと思います)

1. 初期キャンペーンが60000円分あった
2. 支払情報入力しないと”キャンペーン”が作成完了できなかった

**Comment by nishidai-andaze** [comment]
@yofujimaki 

- [ ] [サーチコンソール管理画面](https://search.google.com/search-console/settings/associations?resource_id=sc-domain%3Aandaze.com)　より Google 広告アカウントを承認してください
- [ ] サーチコンソールの nishidai@andaze.com の権限昇格をお願いします（おそらく今後なにかするときに必要そう）

![image](https://user-images.githubusercontent.com/99951437/204418731-8be1fc6f-b135-416c-9d50-b376abde8cdf.png)

**Comment by nishidai-andaze** [comment]
https://ads.google.com/aw/reporting/dashboard/view?ocid=1116849521&starterDashboardId=0&startTour&euid=720648169&__u=4499840481&uscid=1116849521&__c=2111148329&authuser=1

![image](https://user-images.githubusercontent.com/99951437/204530090-4744c452-b61e-474b-9aec-12e3b854044f.png)


とりあえず広告は機能しているらしい

**Comment by nishidai-andaze** [comment]
![image](https://user-images.githubusercontent.com/99951437/204676863-c67646cf-e89c-4e11-a573-a336d786a776.png)

クリック率 0.5%
