### ISSUE TITLE
初回表示のアニメーションないしヴィジュアル

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#64]
https://mathis-biabiany.fr　っぽいガス雲から集まってくる感じ

**Comment by kamihicouki** [comment]
1. ローディング
2. ローディング完了後(初回表示)
3. インタラクティブ操作中(継続表示)

趣旨としては、**実装が比較的簡単そうな 1ないし2の底上げをはかれば全体としてのリッチさ向上につながるのでは？**ないかというもの

DIPのインタラクションが**完全再現できたらそれで綺麗** なんだけど、現状はまだそれには遠いゆえ。
