### ISSUE TITLE
トップのサステナビリティの下に無料ebookのダウンロードセクションを追加

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#694]
- 背景は、とりあえず白
- ダウンロードするとLPのダウンロードページにいく
  - 名前入力なしにいきなり2ファイルが勝手にダウンロード 
- 本セクションはほかのページにも挿入予定なので、部品でつくって再利用可能とする

![image](https://user-images.githubusercontent.com/60770505/202658675-01bdc415-0e83-48df-ad58-a4d05cbb10a4.png)

---

無料PDFブック「PaaSのススメ」持続可能なシステムを「安くつくる」技術（2022年度版）

安価で融通の利くシステム開発について探しているものの、どれもピンとこないと悩んでいませんか？本書は弊社がPaaSを使ってクライアント様の課題を解決し、IT投資を成功させてきたノウハウをご紹介しています。

- DXの成功はプラットホームの所有が鍵
- SaaSのライセンス料を節約し、DXへの投資を成功させる
- データの民主化によって、従業員が高度なデータ活用ができる
- ビジネスの変化に追従できるサステナブルなシステムとは

PaaSを使った持続可能なシステムの作り方と、事前に知っておいていただきたい知識などを100ページ超に渡って詳細に解説しています。ぜひ、貴社のDX化にご活用ください。

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
PaaSのススメ（https://github.com/andaze/landing-page）って本番環境ありましたっけ？
もしあるならリンク教えていただきたいです。

**Comment by nishidai-andaze** [comment]
@TomoyukiHata https://andaze.com/paas-no-susume
