### ISSUE TITLE
ビルドエラーの修正

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#712]
https://github.com/andaze/WebCorporate/actions/runs/3579274452/jobs/6020303363

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
./multiDownload.js, main.jsに記述ミスなどあるのかと思いましたが、そのような個所はなく
ローカル環境では正常に動作します。

一旦ダウンロードセクションにかかわる部分を削除して再pushするという応急処置でも大丈夫ですか？

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
すみません、原因わかりました
multidownloadの綴りミス（multiDownload.jsと書いていた）
