### ISSUE TITLE
新LP の構築（12/19までにリリース）

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#720]
https://andaze.com/lp/1
に以下コンテンツに構築
https://xd.adobe.com/view/e0b3e38c-4423-4359-b34e-bc3ac13b662b-b5e0/

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 

コンポーネント分けしました

https://www.figma.com/file/dmSpwiDIHGVpwUtZQlCmiG/LP%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88?node-id=1%3A59&t=pjfPidr4RZPKATM5-0

**Comment by TomoyukiHata** [comment]
PC(1920px幅）静的コーディング完了（ローカル環境）

**Comment by TomoyukiHata** [comment]
スマホサイズ静的コーディング完了（ローカル環境）

**Comment by TomoyukiHata** [comment]
レスポンシブ対応完了（ローカル環境）

**Comment by nishidai-andaze** [comment]
- [ ] https://github.com/andaze/LandingPages の調整
- [ ] https://github.com/andaze/LandingPages をサブモジュールで取り込み
- [ ] デプロイテスト
- [ ] main merge

**Comment by nishidai-andaze** [comment]
デプロイテスト開始
https://github.com/andaze/WebCorporate/actions/runs/3737559777
