### ISSUE TITLE
LP:複数ファイルのダウンロードは警告が出て止まるので、他の方法を検討して、実装する

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#737]
<img width="785" alt="Snag_134c7dee" src="https://user-images.githubusercontent.com/60770505/206598888-4e3ef117-4805-4b5e-af84-12137836b54f.png">

![image](https://user-images.githubusercontent.com/60770505/206598903-1d5a82d8-5e01-4f34-ad6c-10640dd82792.png)

**Comment by TomoyukiHata** [comment]
@nishidai-andaze 
シンプルにaタグでzipファイルをダウンロードさせるのが良いかと思っているのですが、どう思いますか？

**Comment by nishidai-andaze** [comment]
@TomoyukiHata いいとおもう。
戦略は以下

1. forestory media にアップロードさせる（これは最低限覚えてもらう）。アップロードしたファイル名・パスは控えてもらう
2. md 内（フロントマターまたはショートコード引数）で１．のファイル名を指定したらダウンロードリンクになるようなショートコードまたはテンプレートを作成する
3. 運用する
