### ISSUE TITLE
すべてのページから「アンダーズが擁するプロフェッショナル」を削除

### ISSUE THREAD

**Issue by yofujimaki** [andaze/WebCorporate#780]
- すべてのページから、人の写真を削除する
- オフショアを敬遠する人が結構いるため

![image](https://user-images.githubusercontent.com/60770505/228780130-b398665a-26b1-4c5b-ade5-40d554bda309.png)

**Comment by TomoyukiHata** [comment]
着手

@nishidai-andaze 
ページ構造の整理タスクにconflictするかもしれないと思ったので、pull requestを立てました。

**Comment by TomoyukiHata** [comment]
PRをクローズしてmainブランチに直接push
