### ISSUE TITLE
多言語化の準備

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#8]
* 原稿、日本語しかないけどどうすんね－ん

**Comment by nishidai-andaze** [comment]
DeepL で翻訳して使うらしい

**Comment by nishidai-andaze** [comment]
#47 と関連する

**Comment by nishidai-andaze** [comment]
多言語サイトについては　http://foo.bar/ja/, http://foo.bar/en/ などサブディレクトリ方式を採用する

**Comment by ameio-developer** [comment]
@nishidai-andaze 

https://www.andaze.com/ja/dynamics365
In above link is example site which We have already create with Multilanguage support  
File structure of example site define below screen shoot

![image](https://user-images.githubusercontent.com/79352313/161970643-cec972f4-1b9a-478f-ac34-cbfd3eb78b97.png)

Do we need same structure ?

**Comment by nishidai-andaze** [comment]
@ameio-developer うん。サンプルサイトのコンテツ構造または多言語構造は私が想定しているものと同じだと思います。

サンプルサイトと同じ構造でコーポレートサイトも実装しましょう！

提案いただきありがとうございます。
